#!/bin/bash
# glimpse2_split_reference 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of ref_bcf: '$inp_bcf'"
    echo "Value of ref_idx: '$inp_idx'"
    echo "Value of map: '$map'"
    echo "Value of out_pfx: '$out_pfx'"    
    echo "Value of inp_reg: '$inp_reg'"    
    echo "Value of out_reg: '$out_reg'"
    echo "Value of maf_thr: '$maf_thr'"
    echo "Value of num_thr: '$num_thr'"
    echo "Value of mount_inputs: '$mount_inputs'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".
	
    if [ "$mount_inputs" == "true" ]; then
        dx-mount-all-inputs
    else
        dx-download-all-inputs --parallel
    fi

    ln -s ${inp_bcf_path} ${inp_bcf_name}
    ln -s ${inp_idx_path} ${inp_idx_name}

    if [ -n "$map" ]; then
        ln -s ${map_path} ${map_name}
        map_opt="--m ${map_name}"
    fi
    
    regc=$(echo ${inp_reg} | cut -d":" -f1)
    regs=$(echo ${inp_reg} | cut -d":" -f 2 | cut -d"-" -f1)
    rege=$(echo ${inp_reg} | cut -d":" -f 2 | cut -d"-" -f2)
		
    GLIMPSE2_split_reference --input-region ${inp_reg} --output-region ${out_reg} --output ${out_pfx} --reference ${inp_bcf_name} --sparse-maf ${maf_thr} ${map_opt} --log ${out_pfx}_${regc}_${regs}_${rege}.log --threads ${num_thr} --keep-monomorphic-ref-sites

    out_bin=$(dx upload ${out_pfx}_${regc}_${regs}_${rege}.bin --brief)
    out_log=$(dx upload ${out_pfx}_${regc}_${regs}_${rege}.log --brief)
    
    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    dx-jobutil-add-output out_bin "$out_bin" --class=file
    dx-jobutil-add-output out_log "$out_log" --class=file
}
